version: '3.3'

services:
  app:
    image: docker.pkg.github.com/power-it-dev/template/demo:${VERSION}
    container_name: app
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.app.rule=Host(`ip`)"
      - "traefik.http.routers.app.entrypoints=template"
    depends_on:
      - db
    env_file:
      - .env
    links:
      - "db:db"
    networks:
      - web

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=api
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - web
    expose:
      - 5432
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    networks:
      - web

networks:
  web:
    external: true