version: '3.3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ~/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: .dev
    container_name: app
    links:
      - "db:db"
    env_file:
      - .env
    volumes:
      - .:/var/www/html:delegated
    environment:
      VIRTUAL_HOST: template.loc
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=api
    networks:
      - web
    expose:
      - 5432
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    networks:
      - web

networks:
  web:
    external: true